GET http://localhost:8082/api/logfiles

###

GET http://localhost:8082/api/logfiles/2021-06-27_14-04_TIGERs_Mannheim-vs-ER-Force.log

###

GET http://localhost:8082/api/logfiles/2021-06-27_14-04_TIGERs_Mannheim-vs-ER-Force.log/3/1000000
Accept: application/x-protobuf
