// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_visualization.proto

package visualization

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Color encoded in RGB
type RgbColor struct {
	// red (0-255)
	R uint32 `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	// green (0-255)
	G uint32 `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	// blue (0-255)
	B uint32 `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	// alpha (0.0-1.0)
	A                    float32  `protobuf:"fixed32,4,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RgbColor) Reset()         { *m = RgbColor{} }
func (m *RgbColor) String() string { return proto.CompactTextString(m) }
func (*RgbColor) ProtoMessage()    {}
func (*RgbColor) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2373d4c4bd4508, []int{0}
}

func (m *RgbColor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RgbColor.Unmarshal(m, b)
}
func (m *RgbColor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RgbColor.Marshal(b, m, deterministic)
}
func (m *RgbColor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RgbColor.Merge(m, src)
}
func (m *RgbColor) XXX_Size() int {
	return xxx_messageInfo_RgbColor.Size(m)
}
func (m *RgbColor) XXX_DiscardUnknown() {
	xxx_messageInfo_RgbColor.DiscardUnknown(m)
}

var xxx_messageInfo_RgbColor proto.InternalMessageInfo

func (m *RgbColor) GetR() uint32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *RgbColor) GetG() uint32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *RgbColor) GetB() uint32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *RgbColor) GetA() float32 {
	if m != nil {
		return m.A
	}
	return 0
}

// Metadata for each shape
type Metadata struct {
	// layer name, optionally with a hierarchy
	Layer []string `protobuf:"bytes,1,rep,name=layer,proto3" json:"layer,omitempty"`
	// Should a client show this by default?
	VisibleByDefault bool `protobuf:"varint,2,opt,name=visibleByDefault,proto3" json:"visibleByDefault,omitempty"`
	// An order number:
	// <0: Below field lines
	// 0: default
	// 1: robots
	// 2: robot ids
	// 3: ball
	// >3: above vision objects
	Order int32 `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	// Color to fill the shape
	ColorFill *RgbColor `protobuf:"bytes,4,opt,name=color_fill,json=colorFill,proto3" json:"color_fill,omitempty"`
	// Color for the shape stroke
	ColorStroke          *RgbColor `protobuf:"bytes,5,opt,name=color_stroke,json=colorStroke,proto3" json:"color_stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2373d4c4bd4508, []int{1}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetLayer() []string {
	if m != nil {
		return m.Layer
	}
	return nil
}

func (m *Metadata) GetVisibleByDefault() bool {
	if m != nil {
		return m.VisibleByDefault
	}
	return false
}

func (m *Metadata) GetOrder() int32 {
	if m != nil {
		return m.Order
	}
	return 0
}

func (m *Metadata) GetColorFill() *RgbColor {
	if m != nil {
		return m.ColorFill
	}
	return nil
}

func (m *Metadata) GetColorStroke() *RgbColor {
	if m != nil {
		return m.ColorStroke
	}
	return nil
}

// A line segment
type LineSegment struct {
	// The metadata
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Start point, x value [m]
	StartX float32 `protobuf:"fixed32,2,opt,name=start_x,json=startX,proto3" json:"start_x,omitempty"`
	// Start point, y value [m]
	StartY float32 `protobuf:"fixed32,3,opt,name=start_y,json=startY,proto3" json:"start_y,omitempty"`
	// End point, x value [m]
	EndX float32 `protobuf:"fixed32,4,opt,name=end_x,json=endX,proto3" json:"end_x,omitempty"`
	// End point, y value [m]
	EndY                 float32  `protobuf:"fixed32,5,opt,name=end_y,json=endY,proto3" json:"end_y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineSegment) Reset()         { *m = LineSegment{} }
func (m *LineSegment) String() string { return proto.CompactTextString(m) }
func (*LineSegment) ProtoMessage()    {}
func (*LineSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2373d4c4bd4508, []int{2}
}

func (m *LineSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineSegment.Unmarshal(m, b)
}
func (m *LineSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineSegment.Marshal(b, m, deterministic)
}
func (m *LineSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineSegment.Merge(m, src)
}
func (m *LineSegment) XXX_Size() int {
	return xxx_messageInfo_LineSegment.Size(m)
}
func (m *LineSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_LineSegment.DiscardUnknown(m)
}

var xxx_messageInfo_LineSegment proto.InternalMessageInfo

func (m *LineSegment) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *LineSegment) GetStartX() float32 {
	if m != nil {
		return m.StartX
	}
	return 0
}

func (m *LineSegment) GetStartY() float32 {
	if m != nil {
		return m.StartY
	}
	return 0
}

func (m *LineSegment) GetEndX() float32 {
	if m != nil {
		return m.EndX
	}
	return 0
}

func (m *LineSegment) GetEndY() float32 {
	if m != nil {
		return m.EndY
	}
	return 0
}

// A full circle
type Circle struct {
	// The metadata
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Center point, x value [m]
	CenterX float32 `protobuf:"fixed32,2,opt,name=center_x,json=centerX,proto3" json:"center_x,omitempty"`
	// Center point, y value [m]
	CenterY float32 `protobuf:"fixed32,3,opt,name=center_y,json=centerY,proto3" json:"center_y,omitempty"`
	// Radius [m]
	Radius               float32  `protobuf:"fixed32,4,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Circle) Reset()         { *m = Circle{} }
func (m *Circle) String() string { return proto.CompactTextString(m) }
func (*Circle) ProtoMessage()    {}
func (*Circle) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2373d4c4bd4508, []int{3}
}

func (m *Circle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Circle.Unmarshal(m, b)
}
func (m *Circle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Circle.Marshal(b, m, deterministic)
}
func (m *Circle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Circle.Merge(m, src)
}
func (m *Circle) XXX_Size() int {
	return xxx_messageInfo_Circle.Size(m)
}
func (m *Circle) XXX_DiscardUnknown() {
	xxx_messageInfo_Circle.DiscardUnknown(m)
}

var xxx_messageInfo_Circle proto.InternalMessageInfo

func (m *Circle) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Circle) GetCenterX() float32 {
	if m != nil {
		return m.CenterX
	}
	return 0
}

func (m *Circle) GetCenterY() float32 {
	if m != nil {
		return m.CenterY
	}
	return 0
}

func (m *Circle) GetRadius() float32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

// Wrapper frame containing all shapes
type VisualizationFrame struct {
	// An identifier for the sender
	// Used to identify the source of shapes in a client
	// Also used to keep track of the latest frame of each sender in clients, if there a multiple ones senders
	SenderId string `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// all lines
	Lines []*LineSegment `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	// all circles
	Circles              []*Circle `protobuf:"bytes,3,rep,name=circles,proto3" json:"circles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VisualizationFrame) Reset()         { *m = VisualizationFrame{} }
func (m *VisualizationFrame) String() string { return proto.CompactTextString(m) }
func (*VisualizationFrame) ProtoMessage()    {}
func (*VisualizationFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2373d4c4bd4508, []int{4}
}

func (m *VisualizationFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisualizationFrame.Unmarshal(m, b)
}
func (m *VisualizationFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisualizationFrame.Marshal(b, m, deterministic)
}
func (m *VisualizationFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisualizationFrame.Merge(m, src)
}
func (m *VisualizationFrame) XXX_Size() int {
	return xxx_messageInfo_VisualizationFrame.Size(m)
}
func (m *VisualizationFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_VisualizationFrame.DiscardUnknown(m)
}

var xxx_messageInfo_VisualizationFrame proto.InternalMessageInfo

func (m *VisualizationFrame) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *VisualizationFrame) GetLines() []*LineSegment {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *VisualizationFrame) GetCircles() []*Circle {
	if m != nil {
		return m.Circles
	}
	return nil
}

func init() {
	proto.RegisterType((*RgbColor)(nil), "RgbColor")
	proto.RegisterType((*Metadata)(nil), "Metadata")
	proto.RegisterType((*LineSegment)(nil), "LineSegment")
	proto.RegisterType((*Circle)(nil), "Circle")
	proto.RegisterType((*VisualizationFrame)(nil), "VisualizationFrame")
}

func init() { proto.RegisterFile("ssl_visualization.proto", fileDescriptor_db2373d4c4bd4508) }

var fileDescriptor_db2373d4c4bd4508 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0x99, 0x76, 0xd3, 0x26, 0xa7, 0x15, 0x64, 0x14, 0x37, 0xe2, 0x4d, 0x0d, 0x08, 0x41,
	0xa4, 0x17, 0xeb, 0x1b, 0xec, 0xca, 0x82, 0xa0, 0x37, 0xb3, 0x20, 0xed, 0x55, 0x98, 0x64, 0xce,
	0x86, 0xc1, 0xe9, 0x44, 0x66, 0xa6, 0x4b, 0x23, 0xf8, 0x0e, 0x3e, 0x8f, 0x4f, 0x27, 0x39, 0x93,
	0xac, 0x45, 0x6f, 0xbc, 0xfc, 0xfe, 0xff, 0xe4, 0xe4, 0xff, 0x0f, 0x03, 0x97, 0xde, 0x9b, 0xea,
	0x41, 0xfb, 0xa3, 0x34, 0xfa, 0xbb, 0x0c, 0xba, 0xb3, 0xdb, 0x6f, 0xae, 0x0b, 0x5d, 0x71, 0x0d,
	0xa9, 0x68, 0xeb, 0x9b, 0xce, 0x74, 0x8e, 0xaf, 0x81, 0xb9, 0x9c, 0x6d, 0x58, 0xf9, 0x44, 0x30,
	0xa2, 0x36, 0x9f, 0x45, 0x6a, 0x07, 0xaa, 0xf3, 0x79, 0xa4, 0x7a, 0x20, 0x99, 0x5f, 0x6c, 0x58,
	0x39, 0x13, 0x4c, 0x16, 0xbf, 0x18, 0xa4, 0x9f, 0x31, 0x48, 0x25, 0x83, 0xe4, 0xcf, 0x21, 0x31,
	0xb2, 0xc7, 0x61, 0xd1, 0xbc, 0xcc, 0x44, 0x04, 0xfe, 0x16, 0x9e, 0x3e, 0x68, 0xaf, 0x6b, 0x83,
	0xd7, 0xfd, 0x07, 0xbc, 0x97, 0x47, 0x13, 0x68, 0x77, 0x2a, 0xfe, 0xd1, 0x87, 0x0d, 0x9d, 0x53,
	0xe8, 0xe8, 0x77, 0x89, 0x88, 0xc0, 0x4b, 0x80, 0x66, 0x48, 0x59, 0xdd, 0x6b, 0x63, 0xe8, 0xdf,
	0xab, 0xab, 0x6c, 0x3b, 0x65, 0x17, 0x19, 0x99, 0xb7, 0xda, 0x18, 0xfe, 0x0e, 0xd6, 0x71, 0xd2,
	0x07, 0xd7, 0x7d, 0xc5, 0x3c, 0xf9, 0x7b, 0x76, 0x45, 0xf6, 0x1d, 0xb9, 0xc5, 0x4f, 0x06, 0xab,
	0x4f, 0xda, 0xe2, 0x1d, 0xb6, 0x07, 0xb4, 0x81, 0xbf, 0x81, 0xf4, 0x30, 0x76, 0xa1, 0x5b, 0x0c,
	0x5f, 0x4e, 0xe5, 0xc4, 0xa3, 0xc5, 0x2f, 0x61, 0xe9, 0x83, 0x74, 0xa1, 0x3a, 0x51, 0x8f, 0x99,
	0x58, 0x10, 0xee, 0xfe, 0x18, 0x3d, 0xe5, 0x9f, 0x8c, 0x3d, 0x7f, 0x06, 0x09, 0x5a, 0x55, 0x9d,
	0xc6, 0xbb, 0x5d, 0xa0, 0x55, 0xbb, 0x49, 0xec, 0x29, 0x64, 0x14, 0xf7, 0xc5, 0x0f, 0x58, 0xdc,
	0x68, 0xd7, 0x18, 0xfc, 0xdf, 0x30, 0x2f, 0x21, 0x6d, 0xd0, 0x06, 0x74, 0x8f, 0x69, 0x96, 0x91,
	0x77, 0x67, 0xd6, 0x94, 0x67, 0xb4, 0xf6, 0xfc, 0x05, 0x2c, 0x9c, 0x54, 0xfa, 0xe8, 0xc7, 0x44,
	0x23, 0x15, 0x27, 0xe0, 0x5f, 0xce, 0x5f, 0xca, 0xad, 0x93, 0x07, 0xe4, 0xaf, 0x20, 0xf3, 0x68,
	0x15, 0xba, 0x4a, 0x2b, 0xca, 0x92, 0x89, 0x34, 0x0a, 0x1f, 0x15, 0x2f, 0x20, 0x31, 0xda, 0xa2,
	0xcf, 0x67, 0x9b, 0x79, 0xb9, 0xba, 0x5a, 0x6f, 0xcf, 0x2e, 0x2a, 0xa2, 0xc5, 0x5f, 0xc3, 0xb2,
	0xa1, 0x56, 0x3e, 0x9f, 0xd3, 0xd4, 0x72, 0x1b, 0x5b, 0x8a, 0x49, 0xaf, 0x17, 0xf4, 0x26, 0xdf,
	0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xcd, 0x45, 0xe0, 0xae, 0x02, 0x00, 0x00,
}
